In [55]:
import pandas 
def scrap(date):
    dfs = pandas.read_html("https://rate.bot.com.tw/xrt/all/"+ date )
    return dfs[0]

In [56]:
type(dfs)

list

In [57]:
len(dfs)

1

In [58]:
type(currency.iloc[:,0])

pandas.core.series.Series

In [59]:
currency = dfs[0]

In [60]:
pp = pandas.concat([currency.iloc[:,0],currency.iloc[:,4]],axis=1)

In [61]:
pp

                        幣別 Unnamed: 4_level_0
        Unnamed: 0_level_1               本行賣出
0       美金 (USD)  美金 (USD)             29.625
1       港幣 (HKD)  港幣 (HKD)              3.813
2       英鎊 (GBP)  英鎊 (GBP)              40.44
3       澳幣 (AUD)  澳幣 (AUD)              23.24
4   加拿大幣 (CAD)  加拿大幣 (CAD)              23.74
5   新加坡幣 (SGD)  新加坡幣 (SGD)              22.35
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)              30.54
7       日圓 (JPY)  日圓 (JPY)             0.2653
8     南非幣 (ZAR)  南非幣 (ZAR)               2.41
9     瑞典幣 (SEK)  瑞典幣 (SEK)               3.67
10      紐元 (NZD)  紐元 (NZD)              21.09
11      泰幣 (THB)  泰幣 (THB)             0.9387
12  菲國比索 (PHP)  菲國比索 (PHP)                  -
13    印尼幣 (IDR)  印尼幣 (IDR)                  -
14      歐元 (EUR)  歐元 (EUR)              35.81
15      韓元 (KRW)  韓元 (KRW)                  -
16    越南盾 (VND)  越南盾 (VND)                  -
17    馬來幣 (MYR)  馬來幣 (MYR)                  -
18    人民幣 (CNY)  人民幣 (CNY)              4.575

In [62]:
currency.iloc[:,[0,4]]

                        幣別 Unnamed: 4_level_0
        Unnamed: 0_level_1               本行賣出
0       美金 (USD)  美金 (USD)             29.625
1       港幣 (HKD)  港幣 (HKD)              3.813
2       英鎊 (GBP)  英鎊 (GBP)              40.44
3       澳幣 (AUD)  澳幣 (AUD)              23.24
4   加拿大幣 (CAD)  加拿大幣 (CAD)              23.74
5   新加坡幣 (SGD)  新加坡幣 (SGD)              22.35
6   瑞士法郎 (CHF)  瑞士法郎 (CHF)              30.54
7       日圓 (JPY)  日圓 (JPY)             0.2653
8     南非幣 (ZAR)  南非幣 (ZAR)               2.41
9     瑞典幣 (SEK)  瑞典幣 (SEK)               3.67
10      紐元 (NZD)  紐元 (NZD)              21.09
11      泰幣 (THB)  泰幣 (THB)             0.9387
12  菲國比索 (PHP)  菲國比索 (PHP)                  -
13    印尼幣 (IDR)  印尼幣 (IDR)                  -
14      歐元 (EUR)  歐元 (EUR)              35.81
15      韓元 (KRW)  韓元 (KRW)                  -
16    越南盾 (VND)  越南盾 (VND)                  -
17    馬來幣 (MYR)  馬來幣 (MYR)                  -
18    人民幣 (CNY)  人民幣 (CNY)              4.575

In [65]:
dic={ "2018-01-02":["USD",100],
      "2018-01-04":["USD", 23 ]  
}

In [66]:
for i in dic.keys():
    df=scrap(i)

In [67]:
df

,幣別,現金匯率,Unnamed: 2_level_0,即期匯率,Unnamed: 4_level_0,\n 遠期匯率\n
,Unnamed: 0_level_1,本行買入,本行賣出,本行買入,本行賣出,Unnamed: 5_level_1
0,美金 (USD) 美金 (USD),29.23,29.772,29.53,29.63,查詢
1,港幣 (HKD) 港幣 (HKD),3.638,3.828,3.753,3.813,查詢
2,英鎊 (GBP) 英鎊 (GBP),38.92,40.85,39.79,40.21,查詢
3,澳幣 (AUD) 澳幣 (AUD),22.92,23.58,23.11,23.34,查詢
4,加拿大幣 (CAD) 加拿大幣 (CAD),23.25,23.99,23.52,23.74,查詢
5,新加坡幣 (SGD) 新加坡幣 (SGD),21.75,22.53,22.17,22.35,查詢
6,瑞士法郎 (CHF) 瑞士法郎 (CHF),29.57,30.63,30.1,30.39,查詢
7,日圓 (JPY) 日圓 (JPY),0.2543,0.2653,0.2607,0.2647,查詢
8,南非幣 (ZAR) 南非幣 (ZAR),-,-,2.36,2.44,查詢
9,瑞典幣 (SEK) 瑞典幣 (SEK),3.24,3.75,3.58,3.68,查詢
10,紐元 (NZD) 紐元 (NZD),20.73,21.36,20.97,21.17,查詢
11,泰幣 (THB) 泰幣 (THB),0.8137,0.9567,0.9022,0.9422,查詢
12,菲國比索 (PHP) 菲國比索 (PHP),0.5201,0.6531,-,-,查詢
13,印尼幣 (IDR) 印尼幣 (IDR),0.00188,0.00258,-,-,查詢
14,歐元 (EUR) 歐元 (EUR),34.88,36.03,35.38,35.78,查詢
15,韓元 (KRW) 韓元 (KRW),0.02611,0.03001,-,-,查詢
16,越南盾 (VND) 越南盾 (VND),0.00093,0.00143,-,-,查詢
17,馬來幣 (MYR) 馬來幣 (MYR),6.321,7.911,-,-,查詢
18,人民幣 (CNY) 人民幣 (CNY),4.456,4.618,4.528,4.578,查詢